module Fortran_Kind_Module
 
  implicit none 
 
  ! This Programme was generated by a copyrighted Code.
  ! Author: Werner W Schulz (C) 1998.
 
  ! The following Parameters present all available KIND Values
  ! under the Compiler that generated this Module.
 
  ! Integer KIND Parameters:
  integer, parameter, public ::   Int_01 =  1
  integer, parameter, public ::   Int_02 =  2
  integer, parameter, public ::  Int_Def =  4
  integer, parameter, public ::   Int_08 =  8
  integer, parameter, public ::   Int_16 = 16
 
  ! Real/Complex KIND Parameters:
  integer, parameter, public ::   Single =  4
  integer, parameter, public ::   Double =  8
  integer, parameter, public ::   Extnd1 = 10
  integer, parameter, public ::   Extnd2 = 16
 
end module Fortran_Kind_Module
